#!/usr/bin/env bash
## Description: Recreate the DDEV project, install dependencies, remove canvas module, and print a login URL.
## Usage: demo-setup

set -euo pipefail

ddev delete -O -y
ddev start
ddev composer install

# Remove the canvas module from contrib. Use the one under custom modules.
if [ -d "web/modules/contrib/canvas" ]; then
  echo "Deleting canvas module from contrib: web/modules/contrib/canvas"
  rm -rf web/modules/contrib/canvas
else
  echo "Can't find canvas module at web/modules/contrib/canvas"
fi

ddev drush si ../custom_recipes/findrop -y

if [ -d "web/modules/custom/canvas" ]; then
  pushd web/modules/custom/canvas > /dev/null
  npm install

  if [ -d "ui" ]; then
    pushd ui > /dev/null
    npm run build
    popd > /dev/null
  else
    echo "Can't find UI directory at web/modules/custom/canvas/ui"
    exit 1
  fi

  popd > /dev/null
else
  echo "Can't find custom canvas module at web/modules/custom/canvas"
  exit 1
fi

ddev drush sapi-i
ddev drush cr

ddev drush uli
